### ISSUE TITLE
智午科技 宽午AI大模型

### ISSUE THREAD

**Issue by Nathen888** [wgwang/LLMs-In-China#1]
智午科技  宽午AI  @北京

**Comment by wgwang** [comment]
百度、Google 和公众号都搜了下，没找到相关介绍
方便的话，回复一下相关大模型介绍的文章，有一定权威性的报道或官方网站或试用 demo 等皆可

**Comment by Liuziyue1995** [comment]
ChatLaw-法律大模型 北京大学信息工程学院
https://github.com/PKU-YuanGroup/ChatLaw
