### ISSUE TITLE
关于排序

### ISSUE THREAD

**Issue by ALLinLLM** [wgwang/LLMs-In-China#3]
请说明排序依据，是首字母拼音还是根据别的什么指标

**Comment by wgwang** [comment]
有以下一些排序原则，以下原则有先后顺序：
   本人试用过过的，水平高的排在水平低的前面
   用过的排在没用过的前面
   开源开放的排在封闭的前面 
   基础大模型排在非基础大模型前面，非基础大模型就是之基于基础大模型微调的或者 lora 等
   品牌知名度大的排在知名度小的前面
   有详细介绍的排在没有详细介绍的前面
   出现时间在前面的排在在后面的前面
   名字好听的排在不好听的前面
