### ISSUE TITLE
Phoenix-inst-chat-7b模型

### ISSUE THREAD

**Issue by jiangzhengshen** [wgwang/LLMs-In-China#4]
似乎目前还没收录Phoenix-inst-chat-7b模型，github地址 https://github.com/FreedomIntelligence/LLMZoo

这个模型在[SuperCLUE琅琊榜](https://www.superclueai.com/)上排名还挺靠前的。

**Comment by wgwang** [comment]
加上了，港中文深圳之前有一个华佗 gpt 了，这个漏了
